### ISSUE TITLE
Erreur dans groupement de dossier

### ISSUE THREAD

**Issue by sdis12** [atos-df-rennes/prevarisc#124]
Bonjour,

on met à jour prévarisc selon votre repository et on s'aperçoit qu'un groupement est mis en place pour un établissement seulement ce groupement ne semble pas fonctionner.  (voici le code lié https://github.com/atos-df-rennes/prevarisc/pull/23/commits/64112eac01a1c1d62fb536a66c3589727a580aed)

Quand on regarde sur la capture ci dessous. Les visite corresponde bien à l'id type de dossier 2,3; les Etudes au types dossier 1. Par contre dans autres on retrouve les dossier des groupement visites et autres. Il doit y avoir un erreur dans la manière dont la listes des ID correspondant au autres dossier est faite.

![image](https://github.com/atos-df-rennes/prevarisc/assets/19670448/487211c6-1520-4f58-ac44-a227cc2d40a6)

**Comment by devottered** [comment]
Bonjour !

Comment mettez-vous à jour Prevarisc avec notre repository ?
En effet, le commit que vous mentionnez est le tout premier commit de la fonctionnalité, et il contient effectivement des erreurs. La fonctionnalité a été finalisée dans [cette PR](https://github.com/atos-df-rennes/prevarisc/pull/23) qui a été intégrée dans la branche principale via le commit [eddaa66a93ed77a3ff2f60cf02e22e5d8adfc6fb](https://github.com/atos-df-rennes/prevarisc/commit/eddaa66a93ed77a3ff2f60cf02e22e5d8adfc6fb).

Ce commit contient par ailleurs d'autres évolutions qui nécessitent le passage de fichiers SQL sur la base de données et l'ajout de variables d'environnement ([liste à jour](https://github.com/atos-df-rennes/prevarisc/blob/2.5/docs/documentation_installation.md)).

Cordialement,
Maxime Merrien

**Comment by sdis12** [comment]
Bonjour,

Je viens de prendre connaissance de votre réponse et je vous en remercie.
Concernant prevarisc nous sommes à priori sur cette version https://github.com/atos-df-rennes/prevarisc/commit/baf57a524f16c85632c77c6b214b85f78b146047
Je ne maitrise pas trop github donc pas impossible que j'ai un souci. Je vais reprendre sur notre serveur de test et je vous dis. 

Concernant la base sql j'avais recompilé un peu tout les script qui sont present dans le dossier SQL.
Je vois dans votre lien qu'il est question d'un fichier modèle qui permet de synchroniser le modèle de base de donnée avec sql workbench. Seulement comme indique dans le fichier d'aide, le fichier "docs/MCD Prevarisc avec Mysql Workbench.mwb" n'est pas présent sur le dépot.

**Comment by devottered** [comment]
Bonjour,

Vous êtes donc à jour.
Concernant les fichiers SQLs, nous ne mettons effectivement pas à jour le fichier .mwb mais jouons les fichiers SQLs directement sur la base de données.
Concernant le problème sur les regroupements de dossier, pouvez-vous refaire une vérification ? Cette fonctionnalité étant indépendante du reste, elle devrait être fonctionnelle sur la version que vous mentionnez.

**Comment by sdis12** [comment]
Je profite de rébondir sur ce point mon pb de carto ayant été resolu suite à la dernière mise à jour.
Je viens de faire un git pull sur le dossier prevarisc et je suis bien sur cette id de version (https://github.com/atos-df-rennes/prevarisc/commit/403ac3de8a886eee1d3e17cb4f373f136222371a)

Ca correspond bien aux dernières mise à jour qui inclu bien une carto fonctionnelle.
Si je reprend le dossier d'un établissement. Je retrouver bien dans autres les élément présent à la fois dans visites + Etudes.
Comme ci dessous.

![image](https://github.com/atos-df-rennes/prevarisc/assets/19670448/ee387420-2e35-420a-b9b4-018348843b49)

**Comment by devottered** [comment]
Bonjour,

Merci pour les différents retours !
Je n'avais pas bien vu qu'il s'agissait des mêmes dossiers qui sont répétés dans la section "Autres". Je vais refaire une passe sur ce sujet et vous tiens informé dans ce ticket.

**Comment by devottered** [comment]
Bonjour,

J'ai refais un tour sur ce point et je ne reproduis définitivement pas le souci :/
Les dossiers sont effectivement triés comme suit : Études => ID 1, Visites => ID 2 & 3, Autres => le reste

Reproduisez-vous le problème pour tous les établissements ou celui comportant le problème a-t-il des caractéristiques particulières ?

**Comment by sdis12** [comment]
Bonjour,
Désolé j'etais passé à coté de votre réponse.
De ce que j'ai pu voir ça le fait pour tout les dossiers que j'ai pu passer.

Je pense que le pb doit etre lié à ma base de donnée certainement peut etre un mauvais update quelques part.
Vous m'indiquez que les dossiers sont trier selon ETUDE (id 1) Visites (id 2 et 3) et autres. 
J'imagine que cela correspond à la table dossiertype dans la base prevarisc. Cela semble bon
![image](https://github.com/atos-df-rennes/prevarisc/assets/19670448/c8bec2c2-7327-4062-aa13-14dbc1a4fedd)

Voyez vous d'autres table dans la base qui pourrai poser problème ?

**Comment by devottered** [comment]
Bonjour,

Le tri est effectivement effectué par rapport à cette table. Il n'y a à ma connaissance aucune autre table qui gère d'information sur le type de dossier et la logique de tri n'est pas plus complexe que ce qui est décrit plus haut.

Je pense également qu'il doit y avoir un problème au niveau de la base de données. Cela est tout de même étonnant car bien qu'il y ait un historique sur les établissements, ce n'est pas le cas pour les dossiers.

Pouvez-vous vérifier directement en base de données si les dossiers sont uniques ou s'il y a eu des doublons involontairement créés ? Vous devriez également pouvoir vérifier cela en survolant les liens de chaque dossier et en regardant l'identifiant en fin d'URL. S'ils sont différents, il s'agit très certainement de doublons.

**Comment by sdis12** [comment]
Je viens de vérifier sur 2,3 dossier.
Voici un exemple pour un dossier.
![image](https://github.com/atos-df-rennes/prevarisc/assets/19670448/f3160720-73ab-4768-afc9-a8fafe12817b)

Il apparait en _visite_ et dans _autre_. Le lien du dossier dans les 2 cas fait appel à l'id 18026 dans notre base.

J'ai vérifié sur la table dossier : 
en faisant cette requete : SELECT ID_DOSSIER,TYPE_DOSSIER FROM prevarisc.dossier where ID_DOSSIER=18026;
j'ai bien une seule ligne qui est retournée avec un type de dossier 3 qui correspond à groupe de visite. 
![image](https://github.com/atos-df-rennes/prevarisc/assets/19670448/9a45ef6d-5053-4d4c-b76b-76364a2ab92e)

Je vois pas d'erreur à ce niveau la malheureusement.

**Comment by devottered** [comment]
Bonjour,

Le problème ne vient donc pas de la base de données. Il est très peu probable que cela vienne de la vue également étant donné qu'il y a eu peu de modifications.
La seule explication que je vois en l'état est que le service ne renvoie pas la bonne valeur, peut-être suite à un `git pull` qui s'est mal passé ?

Pouvez-vous regarder dans le fichier `application/services/Etablissement.php` et la fonction `getNLastDossiers` (normalement ligne 508) la ligne concernant l'affectation de la variable `$results['autres']` et vérifier que vous avez la même chose que dans le fichier de ce repo ?

Le cas échéant, n'hésitez pas à me contacter sur cette adresse : maxime.merrien@atos.net

**Comment by devottered** [comment]
Bonjour,

Je ferme cette issue car nous ne reproduisons pas le souci en développement et ne constatons pas le souci chez d'autres SDIS.

N'hésitez pas à ouvrir une nouvelle issue au besoin.
