### ISSUE TITLE
Cartographie HS

### ISSUE THREAD

**Issue by sdis12** [atos-df-rennes/prevarisc#144]
Bonjour,

Depuis quelques jour nous avons la carto IGN est hs sur prévarisc.
La couche ign appelée est pourtant bien lié aux nouvelles url.
![image](https://github.com/atos-df-rennes/prevarisc/assets/19670448/b6c4453a-4ac0-4ac2-80fe-6e02dbdb9411)

Je vois qu'un ticket a aussi été ouvert sur la géoplateforme sur le github du sdis62.
https://github.com/SDIS62/prevarisc/issues/699

Est ce que la carto est toujours censé fonctionner sur votre version ?

Merci pour cette précision.

Cordialement,

**Comment by devottered** [comment]
Bonjour,

La cartographie IGN bascule effectivement du géoportail (URLs en wsx.ign) vers la géoplateforme (URLs en data.geopf). L'URL est presque correcte puisqu'il manque le "s" à la fin de "wmts" ! (effet de bord du code applicatif suite au changement d'URLs)
Nous avons effectué la [mise à jour du code applicatif](https://github.com/atos-df-rennes/prevarisc/commit/b623ad3d9c488c8d47145c873b10742a07d60ef8) à l'instant. Petite précision si vous utilisez un fichier d'autoconfiguration plutôt que les clés en direct, il faut générer le fichier via [cette URL](https://geoplateforme-configuration.onrender.com/) (le renseignement de la clé privée n'est pas obligatoire)

N'hésitez pas à revenir vers moi en cas de difficulté ou si vous constatez un problème suite à la bascule !
Cordialement,
Maxime Merrien
