### ISSUE TITLE
Problème dans le module de téléchargement des pièces jointes  get-zip-all-pj

### ISSUE THREAD

**Issue by SDIS91** [atos-df-rennes/prevarisc#179]
Bonjour,

Pour un grand nombre de pièces jointes (fichiers volumineux de plus de  60 Mo), le zip téléchargé est vide !

c'est combien la limite maximale des PJ que le module peut supporter ? y'a t 'il une solution à ce problème ?

Merci d'avance.

Le webmaster de SDIS91

**Comment by devottered** [comment]
Bonjour,

Pouvez-vous m'indiquer si vous constatez une erreur au niveau des logs Apache lorsque vous téléchargez le zip ?
Il n'y a pas de limite à proprement parler pour cette fonctionnalité mais il est effectivement possible que la mémoire PHP ne suffise pas s'il y a un grand nombre de fichiers volumineux.
Vous pouvez essayer de l'augmenter dans le fichier de configuration PHP **php.ini** comme solution temporaire. Je vais également effectuer des tests de mon côté.

Cordialement,
Maxime Merrien

**Comment by SDIS91** [comment]
Bonjour,

Merci pour votre réponse rapide.

le message d'erreur d'apache est toujours mémoire insuffisante et portant on est allé jusqu'à 1024 Mo.
NB : le nombre de fichiers à zipper est de l'ordre de 90 avec un poids total de 870 Mo (envoyer par plat'au).

Cordialement
Le webmastrer SDSI91

**Comment by devottered** [comment]
Bonjour,

Pour information, le souci est effectivement lié à une mémoire PHP insuffisante pour télécharger tous les documents en une seule fois. Je suis en train de regarder s'il est possible de détecter ce souci avant le téléchargement et pouvoir ainsi ajuster le téléchargement pour éventuellement avoir plusieurs fichiers ZIP de sortie.

Maxime

**Comment by SDIS91** [comment]
Merci, nous regardons aussi de notre coté

**Comment by devottered** [comment]
Bonjour @SDIS91,

Nous avons fait une correction qui permet de traiter le téléchargement du ZIP petit à petit. Cela pourra éventuellement prendre un peu de temps pour de gros fichiers mais tout le contenu devrait être présent à la fin !

N'hésitez pas à me faire un retour,
Maxime

**Comment by SDIS91** [comment]
Merci
Nous allons tester et revenir vers vous.
