### ISSUE TITLE
Permettre l'utilisation multi-clés pour la cartographie IGN

### ISSUE THREAD

**Issue by devottered** [atos-df-rennes/prevarisc#29]
Suite aux changements effectués dernièrement par l'IGN, il faut pouvoir utiliser plusieurs clés pour :

- [x] #30
- [x] #31
- [x] Pouvoir modifier l'ordre des couches

cf. https://github.com/atos-df-rennes/prevarisc/pull/28

**Comment by devottered** [comment]
Quelques problèmes persistent :

- Le format n'est pas toujours correct pour les couches WMS
  - [x] Permettre aux utilisateurs de choisir le format de la couche si elle est de type WMS
- Du fait des nombreuses requêtes, le temps de chargement sur la page d'ajout des couches est élevé
  - [x] Utiliser l'autoconf pour réduire le nombre de requêtes pour les couches de type WMS => Très rapide désormais, problème côté IGN (à surveiller)

**Comment by SDIS83Loic** [comment]
L'ajout du service WMTS semble maintenant nécessaire pour le service IGN (les couches ortho, bati, et autres...).
Actuellement seul le service WMS en Scan25 reste disponible.

**Comment by devottered** [comment]
Le service WMTS va être ajouté sur la [PR associée](https://github.com/atos-df-rennes/prevarisc/pull/28).

Nous avons modifié l'interface d'ajout des couches IGN pour simplifier l'utilisation et limiter les erreurs. Comme mentionné dans le commentaire précédent, le problème majeur est le temps de chargement des informations relatives aux couches disponibles, du fait du passage en multi-clés (il faut requêter les couches pour chaque clé)

Concernant les données en Scan25, il me semble que ces données restent disponibles sur une clé individuelle. L'idée est maintenant de passer sur le système de clés génériques de l'IGN (découverte, inspire, essentiels, ou experts : adresse, cartes, cartovecto, ...) dont vous pouvez retrouver la liste sur le site de l'IGN : https://geoservices.ign.fr/services-web-experts
