### ISSUE TITLE
Erreur 'Zend_Log_Exception'

### ISSUE THREAD

**Issue by nikown** [atos-df-rennes/prevarisc#3]
Bonjour,
Je souhaite installer la MAJ 2.5 de Prevarisc en test pour le SDIS 11 mais je me heurte à un problème.
Après l'installation, l'appli affiche page blanche (seul la favicon de prevarisc est présente).

Voici ce que me sort le fichier error.log d'apache:

[Thu Feb 13 09:34:28.511679 2020] [:error] [pid 8064] [client 195.99.2.8:35655] PHP Fatal error:  Uncaught exception 'Zend_Log_Exception' with message '"/app-error_log" cannot be opened with mode "a"' in /var/www/v2/Prevarisc/vendor/zendframework/zendframework1/library/Zend/Log/Writer/Stream.php:81\nStack trace:\n#0 /var/www/v2/Prevarisc/application/Bootstrap.php(175): Zend_Log_Writer_Stream->__construct('/app-error_log')\n#1 /var/www/v2/Prevarisc/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/BootstrapAbstract.php(681): Bootstrap->_initLog()\n#2 /var/www/v2/Prevarisc/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/BootstrapAbstract.php(634): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource('log')\n#3 /var/www/v2/Prevarisc/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/BootstrapAbstract.php(598): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap(NULL)\n#4 /var/www/v2/Prevarisc/vendor/zendframework/zendframework1/library/Zend/Application.php(373): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap(NULL)\n#5 /var/www/v in /var/www/v2/Prevarisc/vendor/zendframework/zendframework1/library/Zend/Log/Writer/Stream.php on line 81

J'ai remarqué que le fichier qui pose problème "Bootstrap.php" a été modifié il n'y à paés longtemps aux lignes qui ont l'air de poser problèmes.

voir le commit sur ce fichier:
https://github.com/atos-df-rennes/prevarisc/commit/0731e5ff947a0f22796ddf1a836760cb8e2f7d8a

Cela fait quelques jours que je cherche sans trouver mon bonheur.
Si quelqu'un peut m'aider ?

Cordialement
Nicolas Decor - Service SITC - SDIS 11

**Comment by devottered** [comment]
Bonjour,

Effectivement le fichier posant problème est le fichier "Bootstrap.php".
A priori il s'agit d'un problème de droits sur le dossier / fichier de log. Le problème étant qu'avec l'erreur, le fichier ne se crée pas, donc il n'est pas possible de donner les droits au fichier.

En attendant de trouver une solution permettant d'utiliser ce fichier, vous pouvez commenter la dernière fonction du fichier "Bootstrap.php" : _initLog

Cela rétablira l'affichage !

Cordialement

**Comment by nikown** [comment]
Bonjour,
J'accède bien au site en commentant les lignes du fichier "Bootstrap.php" 

J'ai par contre une erreur PHP en voulant créer un établissement.

Fatal error: Uncaught exception 'Zend_Db_Table_Row_Exception' with message 'Specified column "DATESUPPRESSION_ETABLISSEMENT" is not in the row' in /var/www/v2/Prevarisc/vendor/zendframework/zendframework1/library/Zend/Db/Table/Row/Abstract.php:179 Stack trace: #0 /var/www/v2/Prevarisc/vendor/zendframework/zendframework1/library/Zend/Db/Table/Row/Abstract.php(280): Zend_Db_Table_Row_Abstract->__get('DATESUPPRESSION...') #1 /var/www/v2/Prevarisc/application/services/Etablissement.php(45): Zend_Db_Table_Row_Abstract->offsetGet('DATESUPPRESSION...') #2 /var/www/v2/Prevarisc/application/plugins/ACL.php(406): Service_Etablissement->get('9677') #3 /var/www/v2/Prevarisc/application/plugins/ACL.php(340): Plugin_ACL->getEtablissementPageResourses('9677') #4 /var/www/v2/Prevarisc/application/plugins/ACL.php(240): Plugin_ACL->getPageResources(Object(Zend_Navigation_Page_Mvc), Object(Zend_Controller_Request_Http)) #5 /var/www/v2/Prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php(309): Plugin_ACL->p in /var/www/v2/Prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php on line 312

Ainsi qu'une erreur SQL en voulant rechercher un établissement.

Problème de recherche La recherche n'a pas été effectuée correctement. Veuillez réessayer. (SQLSTATE[42S22]: Column not found: 1054 Unknown column 'etablissement.DATESUPPRESSION_ETABLISSEMENT' in 'where clause', query was: SELECT `e`.`NUMEROID_ETABLISSEMENT`, `e`.`DUREEVISITE_ETABLISSEMENT`, `e`.`NBPREV_ETABLISSEMENT`, ( SELECT COUNT(etablissementlie.ID_FILS_ETABLISSEMENT) FROM etablissement INNER JOIN etablissementlie ON etablissement.ID_ETABLISSEMENT = etablissementlie.ID_ETABLISSEMENT WHERE etablissement.ID_ETABLISSEMENT = e.ID_ETABLISSEMENT AND etablissement.DATESUPPRESSION_ETABLISSEMENT IS NULL) AS `NB_ENFANTS`, (SELECT COUNT(dossierlie.ID_DOSSIER1) FROM dossier INNER JOIN etablissementdossier ON dossier.ID_DOSSIER = etablissementdossier.ID_DOSSIER INNER JOIN dossierlie ON dossier.ID_DOSSIER = dossierlie.ID_DOSSIER2 INNER JOIN dossiernature ON dossierlie.ID_DOSSIER1 = dossiernature.ID_DOSSIER WHERE dossiernature.ID_NATURE = 46 AND etablissementdossier.ID_ETABLISSEMENT = e.ID_ETABLISSEMENT AND dossier.DATESUPPRESSION_DOSSIER IS NULL) AS `PRESENCE_ECHEANCIER_TRAVAUX`, `etablissementinformations`.*, `dossier`.`DATEVISITE_DOSSIER`, `dossier`.`DATECOMM_DOSSIER`, `dossier`.`DATEINSERT_DOSSIER`, `dossier`.`DIFFEREAVIS_DOSSIER`, `avis`.*, `type`.`LIBELLE_TYPE`, `typeactivite`.`LIBELLE_ACTIVITE`, `genre`.`LIBELLE_GENRE`, `etablissementlie`.`ID_ETABLISSEMENT` AS `pere`, `etablissementlie`.`ID_FILS_ETABLISSEMENT`, `etablissementadresse`.`NUMINSEE_COMMUNE`, `etablissementadresse`.`LON_ETABLISSEMENTADRESSE`, `etablissementadresse`.`LAT_ETABLISSEMENTADRESSE`, `etablissementadresse`.`ID_ADRESSE`, `etablissementadresse`.`ID_RUE`, `etablissementadresse`.`NUMERO_ADRESSE`, `adressecommune`.`LIBELLE_COMMUNE` AS `LIBELLE_COMMUNE_ADRESSE_DEFAULT`, `adresserue`.`LIBELLE_RUE`, `etablissementadressesite`.`ID_RUE` AS `ID_RUE_SITE`, `adressecommunesite`.`LIBELLE_COMMUNE` AS `LIBELLE_COMMUNE_ADRESSE_SITE`, `etablissementadressecell`.`ID_RUE` AS `ID_RUE_CELL`, `adressecommunecell`.`LIBELLE_COMMUNE` AS `LIBELLE_COMMUNE_ADRESSE_CELLULE` FROM `etablissement` AS `e` INNER JOIN `etablissementinformations` ON e.ID_ETABLISSEMENT = etablissementinformations.ID_ETABLISSEMENT AND etablissementinformations.DATE_ETABLISSEMENTINFORMATIONS = ( SELECT MAX(etablissementinformations.DATE_ETABLISSEMENTINFORMATIONS) FROM etablissementinformations WHERE etablissementinformations.ID_ETABLISSEMENT = e.ID_ETABLISSEMENT ) LEFT JOIN `dossier` ON e.ID_DOSSIER_DONNANT_AVIS = dossier.ID_DOSSIER LEFT JOIN `avis` ON dossier.AVIS_DOSSIER_COMMISSION = avis.ID_AVIS LEFT JOIN `type` ON etablissementinformations.ID_TYPE = type.ID_TYPE LEFT JOIN `typeactivite` ON etablissementinformations.ID_TYPEACTIVITE = typeactivite.ID_TYPEACTIVITE INNER JOIN `genre` ON etablissementinformations.ID_GENRE = genre.ID_GENRE LEFT JOIN `etablissementlie` ON e.ID_ETABLISSEMENT = etablissementlie.ID_FILS_ETABLISSEMENT LEFT JOIN `etablissementadresse` ON e.ID_ETABLISSEMENT = etablissementadresse.ID_ETABLISSEMENT LEFT JOIN `adressecommune` ON etablissementadresse.NUMINSEE_COMMUNE = adressecommune.NUMINSEE_COMMUNE LEFT JOIN `adresserue` ON adresserue.ID_RUE = etablissementadresse.ID_RUE LEFT JOIN `etablissementadresse` AS `etablissementadressesite` ON etablissementadressesite.ID_ETABLISSEMENT = (SELECT ID_FILS_ETABLISSEMENT FROM etablissementlie WHERE ID_ETABLISSEMENT = e.ID_ETABLISSEMENT LIMIT 1) LEFT JOIN `adressecommune` AS `adressecommunesite` ON etablissementadressesite.NUMINSEE_COMMUNE = adressecommunesite.NUMINSEE_COMMUNE LEFT JOIN `etablissementadresse` AS `etablissementadressecell` ON etablissementadressecell.ID_ETABLISSEMENT = (SELECT ID_ETABLISSEMENT FROM etablissementlie WHERE ID_FILS_ETABLISSEMENT = e.ID_ETABLISSEMENT LIMIT 1) LEFT JOIN `adressecommune` AS `adressecommunecell` ON etablissementadressecell.NUMINSEE_COMMUNE = adressecommunecell.NUMINSEE_COMMUNE WHERE (e.DATESUPPRESSION_ETABLISSEMENT IS NULL) GROUP BY `e`.`ID_ETABLISSEMENT` LIMIT 50)


Je ne sais pas si ces erreurs sont du à une mauvaise installation de ma part ou à un problème sur cette version, dans le doute je préfère partager.

**Comment by devottered** [comment]
Bonjour,

Réponse un peu tardive, mais il y a effectivement eu des ajouts dans cette version.
La possibilité de **supprimer un établissement ou un dossier** a notamment été ajoutée, une **modification de la base SQL** doit donc être effectuée.

Pour faciliter la résolution du problème, allez sur la page de recherche des établissements. L'erreur devrait apparaître, et aucun établissement ne devrait être visible.

Pour effectuer la modification, ajoutez le code suivant dans un fichier SQL (**e.g.** ajoutDroitSuppression.sql) :
```
set names 'utf8';

#Ajout de la resource de suppression
INSERT INTO `resources` (`id_resource`, `name`, `text`) VALUES (60, 'suppression', 'Suppression');

#Ajout des privileges de suppression
INSERT INTO `privileges` (`id_privilege`, `name`, `text`, `id_resource`) VALUES (70, 'delete_dossier', 'Suppression des dossiers', 60);
INSERT INTO `privileges` (`id_privilege`, `name`, `text`, `id_resource`) VALUES (71, 'delete_etablissement', 'Suppression des établissements', 60);

#Ajout flag dossier pour suppression
ALTER TABLE `dossier` ADD DATESUPPRESSION_DOSSIER DATE;

#Ajout flag etablissement pour suppression
ALTER TABLE `etablissement` ADD DATESUPPRESSION_ETABLISSEMENT DATE;
```

Jouez ensuite le fichier SQL sur la base cible. Rafraîchissez la page de recherche des établissements, l'erreur sera sans doute encore affichée, mais **les établissements devraient être visibles**, et vous devriez pouvoir y accéder.

Vous pourrez ensuite paramétrer la ressource de suppression d'établissement et de dossier en fonction des groupes d'utilisateurs.

En espérant que ceci résoudra ce problème,
Cordialement

**Comment by devottered** [comment]
Je ferme cette issue car l'amélioration concernant le fichier de log applicatif n'est pas essentielle et pose trop de souci.
