### ISSUE TITLE
Geolocasation d'adresse

### ISSUE THREAD

**Issue by sdis12** [atos-df-rennes/prevarisc#56]
Bonjour,

On s'aperçoit que la géolocalisation pour une adresse ne semble plus fonctionner (bouton Géoportail).

Sur la fenetre ci dessous quand on clique sur le bouton Géolocaliser cette adrese (Geoportail), géolocalisation en cours s'affiche mais aucune carte de l'ign ne s'affiche.
![image](https://user-images.githubusercontent.com/19670448/200521275-b89b6803-162e-48f5-bf83-f863b9105a58.png)

Quand je regarde sur le debugger chrome j'ai ce tuype d'erreur qui est visible : 
![image](https://user-images.githubusercontent.com/19670448/200521830-6b77578d-4ca1-4fa1-81ab-3e88a3b5d016.png)

Quand on regarde le log l'URL sur l'ign générée contien la clée IGN paramétré sur notre serveur prévarisc. 
Notre cartographe nous indique que cette clée n'est normalement plus utile. Il ne peut pas en générer une nouvelle.

Est ce que vous avez le même comportement ? 
Voyez vous un moyen de résoudre ce problème ?
J'ai passé les dernières mise à jour mais ça n'a rien changé en regardant les modif il n'y avait pas d'éléments liés à cette problématique.

Merci d'avance pour votre aide.

**Comment by devottered** [comment]
Bonjour,

Il y a effectivement eu une [mise à jour](https://github.com/atos-df-rennes/prevarisc/pull/28) au niveau de la cartographie liée au fait que les clés personnelles ne sont plus utiles, comme indiqué par votre cartographe.
Il existe désormais des clés libres d'accès dont une liste est disponible ici : [Clé essentiels](https://geoservices.ign.fr/services-web-essentiels) / [Clés expertes](https://geoservices.ign.fr/services-web-experts)

Pour que cela fonctionne, il faut modifier une variable dans le fichier de configuration de Prevarisc :
`SetEnv PREVARISC_PLUGIN_IGNKEY "essentiels,adresse,administratif,cartes,cartovecto,topographie,geodesie,parcellaire"`
Comme vous pouvez le voir, il est possible d'indiquer une ou plusieurs clés.

Après avoir renseigné les clés, il faut aller dans l'administration et ajouter des couches IGN :
![image](https://user-images.githubusercontent.com/48253852/202197315-23a75a79-31ff-4206-915d-b95b6a87c5c4.png)
Ce passage est obligatoire, même si une couche avait déjà été renseignée, afin que les URLs soient de nouveau valides.
L'interface pour l'ajout des couches IGN a changée et propose désormais automatiquement les couches liées aux clés renseignées dans la configuration.

N'hésitez pas à revenir vers moi en cas de problème,
Cordialement,
Maxime Merrien

**Comment by devottered** [comment]
Bonjour,

Avez-vous pu remettre en place la cartographie avec les éléments apportés dans la précédente réponse ?

Cordialement,
Maxime Merrien

**Comment by sdis12** [comment]
Bonjour,

Merci beaucoup pour votre réponse. J'etais passé un peu a coté. 
Entre temps on avait changé la clé avec essentiels et au bout d'un moment le service etait revenu mais merci pour les info supplémentaire sur les différentes clés.
